### ISSUE TITLE
Official?

### ISSUE THREAD

**Issue by efrecon** [docker-library/healthcheck#11]
Maybe this isn't the proper place to ask, but is there any particular reason the prototyping that has occurred within these images haven't made its way into the official images? `HEALTHCHECK` is an advertised feature of `Dockerfile`s and it feels that official images should show the way forward and demonstrate how to check upon themselves.

**Comment by tianon** [comment]
Yes, see https://github.com/docker-library/cassandra/pull/76#issuecomment-246054271 (which we should add to the `README` here as well).

**Comment by efrecon** [comment]
Thanks for the reply. I found the thread that you are referring to a bit later. As future is kind of uncertain, I went for a [solution](https://hub.docker.com/r/efrecon/redis/) that should provide all redis images at once, now and forward. I think that the idea should be applicable to most images, but with a different `HEALTHCHECK` that is. My hooks for [build](https://github.com/efrecon/docker-images/blob/master/healthcheck/redis/hooks/build) and [push](https://github.com/efrecon/docker-images/blob/master/healthcheck/redis/hooks/push) are more or less image independent. BTW, I blatantly stole your redis HEALTHCHECK code, hope this is ok.

**Comment by efrecon** [comment]
Would you accept PRs for these files (and dirs). I am slowly putting into place solutions that do not require bash (so they can run on top of Alpine as well) and can automatically be built. Migrating this might however need some changes to the various settings on the [hub](https://hub.docker.com/r/healthcheck/).

**Comment by efrecon** [comment]
ping?

**Comment by tianon** [comment]
Sorry for the delay.

> BTW, I blatantly stole your redis HEALTHCHECK code, hope this is ok.

Absolutely, that's the whole point of this repository!

See https://github.com/docker-library/cassandra/pull/76#issuecomment-246054271 -- this repository exists precisely as an _example_ for users to set up their own `HEALTHCHECK`s which are relevant to their deployments.  Many users are going to need modifications, etc, which is why I'd honestly not recommend users use these images directly, and why I'd be hesitant to do things like tag multiple versions which might encourage more users to do so.

**Comment by tianon** [comment]
See https://github.com/docker-library/faq#healthcheck for more detail about why these are intentionally separate.
